# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-19 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171216_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='accounts/uploads'),
        ),
    ]
